### ISSUE TITLE
Mise à jour du theme /!\

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/bordeauxmontaigne-nousnavonspasnumerise#4]
Hello ! On ne peut pas mettre à jour le thème car vous avez écrasé les fichiers de config 
Il faut simplement redéfinir les variables dans configuration.sass

https://github.com/osunyorg/bordeauxmontaigne-nousnavonspasnumerise/tree/main/assets/sass/_theme

**Comment by arthaud-proust** [comment]
Hello Clara ! Navré de te causer du soucis pour la maj, je ne suis pas sur de comprendre ce qu'il faut faire 
Nous avons modifié le sass pour faire notre propre thème dans le dossier que tu as indiqué (/assets/sass/_theme) il faudrait appliquer nos styles autrement donc ?

Est-ce que la maj du thème est obligatoire ?

**Comment by Clararigaud** [comment]
Hello ! En fait vous avez copié des fichiers du theme que vous avez modifié ensuite. 
La conséquence c'est que à la mise à jour du theme, certaines variables ne sont plus nommées de la meme manière, et ça casse tout. 
La bonne manière de faire c'est simplement de créer un ou plusieurs fichiers sass qui redéfinissent uniquement les styles dont vous avez besoin. 
C'est expliqué ici > https://developers.osuny.org/docs/website/coder-le-side/css/ 
Et tu peux regarder comment c'est fait ici par exemple > https://github.com/osunyorg/vigo-postgrowth-lab/tree/main/assets/sass 


La maj n'est pas obligatoire, mais c'est dommage car votre site est super et on pourrait continuer à le maintenir avec les maj du theme et le mettre en valeur, si il ne peut pas être mis à jour on va devoir l'enlever.

**Comment by arthaud-proust** [comment]
Ok je comprends mieux, merci de la clarification ! Je vais m'en occuper ce soir alors

**Comment by arthaud-proust** [comment]
je suis pas sûr de pouvoir faire grand chose de plus ce soir : nous avons copié collé les fichiers sass du thème et les avons modifiés ce qui cache nos modifications du thème. On peut faire un diff entre les [fichiers sass du thème](https://github.com/osunyorg/theme/tree/v6.0.0/assets/sass/_theme) et [ceux qu'on a dans le repo](https://github.com/osunyorg/bordeauxmontaigne-nousnavonspasnumerise/tree/main/assets/sass/_theme) pour extraire nos modifs et y voir plus clair sur ce qu'il faudrait corriger.

Cependant, je ne sais pas si ça a du sens de mettre à jour un site qui n'a plus besoin d'être modifié, ni dans le contenu, ni dans l'apparence.

J'ai build et mis sur https://nousnavonspasnumerise.netlify.app/ le backup html/css de la dernière version du projet. C'est un peu "définitif" mais bon :) (https://github.com/arthaud-proust/nousnavonspasnumerise)

@EmmaGuillaume @simdgtk je sais pas si vous avez le temps de corriger ce que @Clararigaud a énoncé plus haut, je propose la solution du backup en attendant car je n'ai pas plus de temps à allouer cette semaine...

**Comment by arthaud-proust** [comment]
Coucou @arnaudlevy, je sais pas ce que tu en penses, mais si on garde l'option du build uniquement, est-ce que ce sera possible pour vous de faire rediriger nousnavonspasnumerise.mmibordeaux.com/* vers nousnavonspasnumerise.netlify.app ? Pour conserver le seo/liens linkedins etc

**Comment by arnaudlevy** [comment]
@arthaud-proust je pense qu'on va arriver à résoudre ça proprement :)
C'est mieux que ce soit chez Deuxfleurs, vu le thème.

**Comment by arnaudlevy** [comment]
@Clararigaud tu peux aider @arthaud-proust à ranger tu crois ? Merci beaucoup !

**Comment by Clararigaud** [comment]
ok je vais regarder

**Comment by Clararigaud** [comment]
Coucou ! Alors j'ai fait un bon gros nettoyage, il reste quelques petites choses à améliorer mais au moins le site compile avec le nouveau theme :) 
J'ai cassé ça aussi : je vous laisse regarder héhé
<img width="640" alt="image" src="https://github.com/osunyorg/bordeauxmontaigne-nousnavonspasnumerise/assets/2864241/f351dd6c-9703-4b55-8885-feba2371ea25">

**Comment by arthaud-proust** [comment]
merci beaucoup @Clararigaud ! 
Oui effectivement @arnaudlevy, un hébergement chez deux fleurs fait plus de sens que chez netlify. 
L'envie de prendre du temps pour gérer ce sujet ne manque pas de mon côté, mais pour l'instant je ne peux pas.
Je laisse les autres membres du projet prendre le relai @simdgtk @EmmaGuillaume ou Matthieu Marchand

**Comment by simdgtk** [comment]
Oui très bien je vais regarder ça, merci beaucoup @Clararigaud  pour l'aide
